epicaTTA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pica.urls')),    # Homepage
    path('users/', include('users.urls')), # Dashboard
    path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:  # Dev only
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pica/urls.py
from django.urls import path
from . import views

app_name = 'pica'

urlpatterns = [
    # Home
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # InCharge
    path('search_incharge/<uuid:id>/<str:op>/<uuid:tpk>/', views.search_incharge,
         name="search_incharge"),
    path('add_inputter_to_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/<str:st>/', views.add_inputter_to_topic,
         name="add_inputter_to_topic"),
    path('add_incharge_to_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.add_incharge_to_topic,
         name="add_incharge_to_topic"),
    path('delete_inputter_from_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.delete_inputter_from_topic,
         name="delete_inputter_from_topic"),
    path('delete_incharge_from_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.delete_incharge_from_topic,
         name="delete_incharge_from_topic"),

    # Company
    path('list_company/', views.list_company, name="list_company"),
    path('input_company/', views.InputCompanyView.as_view(), name="input_company"),
    path('update_company/<uuid:id>/', views.UpdateCompanyView.as_view(), name="update_company"),
    path('delete_company/<uuid:id>/', views.DeleteCompanyView.as_view(), name="delete_company"),

    # Forum
    path('list_forum/', views.list_forum, name="list_forum"),
    path('input_forum/', views.InputForumView.as_view(), name="input_forum"),
    path('update_forum/<uuid:id>/', views.UpdateForumView.as_view(), name="update_forum"),
    path('delete_forum/<uuid:id>/', views.DeleteForumView.as_view(), name="delete_forum"),

    # Meeting
    path('list_meeting/<str:op>/', views.list_meeting, name="list_meeting"),
    path('list_complete_approve/', views.list_complete_approve, name="list_complete_approve"),
    path('input_attachment/<uuid:id>/<str:op>/', views.InputAttachmentView.as_view(), name="input_attachment"),
    path('input_activity_attachment/<uuid:id>/<uuid:id2>/', views.InputActivityAttachmentView.as_view(),
         name="input_activity_attachment"),
    path('delete_lampiran/<uuid:id>/<str:op>/<uuid:id2>/', views.delete_lampiran, name="delete_lampiran"),
    path('delete_pdf/<uuid:id>/<uuid:id2>/', views.delete_pdf, name="delete_pdf"),
    path('delete_image/<uuid:id>/<uuid:id2>/', views.delete_image, name="delete_image"),
    path('input_meeting/<str:op>/', views.InputMeetingView.as_view(), name="input_meeting"),
    path('update_meeting/<uuid:id>/<str:op>/', views.UpdateMeetingView.as_view(), name="update_meeting"),

    # Meeting Approved
    path('list_meeting_pending/', views.list_meeting_pending, name="list_meeting_pending"),
    path('list_topic_review/<uuid:id>/', views.list_topic_review, name="list_topic_review"),
    path('review_topic/<uuid:tpk>/<uuid:apr>/', views.ReviewTopicView.as_view(), name="review_topic"),
    path('approve_meeting/<uuid:id>/', views.ApproveMeetingView.as_view(), name="approve_meeting"),

    # Outside Participant
    path('list_outside/', views.list_outside, name="list_outside"),
    path('input_outside/', views.InputOutsideView.as_view(), name="input_outside"),
    path('update_outside/<uuid:id>/', views.UpdateOutsideView.as_view(), name="update_outside"),
    path('update_outside_participant/<uuid:id>/<str:op>/', views.update_outside_participant,
         name="update_outside_participant"),
    path('add_outside_to_meeting/<uuid:meet>/<uuid:id>/<str:op>/', views.add_outside_to_meeting,
         name="add_outside_to_meeting"),
    path('delete_outside_from_meeting/<uuid:meet>/<uuid:id>/<str:op>/', views.delete_outside_from_meeting,
         name="delete_outside_from_meeting"),
    path('delete_outside/<uuid:id>/', views.DeleteOutsideView.as_view(), name="delete_outside"),

    # Topic
    path('input_topic/<uuid:id>/<str:op>/', views.InputTopicView.as_view(), name="input_topic"),
    path('update_pic_topic/<uuid:meet>/<uuid:id>/<str:op>/', views.update_pic_topic, name="update_pic_topic"),
    path('update_topic/<uuid:meet>/<uuid:id>/<str:op>/', views.UpdateTopicView.as_view(), name="update_topic"),
    path('add_pic_to_topic/<uuid:tpk>/<int:id>/<str:op>/', views.add_pic_to_topic,
         name="add_pic_to_topic"),
    path('delete_pic_from_topic/<uuid:tpk>/<int:id>/<str:op>/', views.delete_pic_from_topic,
         name="delete_pic_from_topic"),
    path('list_topic/<uuid:id>/<str:op>/', views.list_topic, name="list_topic"),
    path('overdue_all_pica/', views.overdue_all_pica, name='overdue_all_pica'),
    path('ongoing_all_pica/', views.ongoing_all_pica, name='ongoing_all_pica'),
    path('close_pica/<uuid:id>/', views.close_pica, name='close_pica'),
    path('change_pica_status/<uuid:id>/', views.change_pica_status, name='change_pica_status'),

    # Workflow
    path('update_workflow/<uuid:id>/', views.update_workflow, name="update_workflow"),
    path('update_cpmd/<uuid:id>/', views.update_cpmd, name="update_cpmd"),
    path('update_secretary/<uuid:id>/', views.update_secretary, name="update_secretary"),
    path('edit_workflow/<uuid:id>/<uuid:forum>/', views.EditWorkflowView.as_view(), name="edit_workflow"),
    path('add_bod_to_workflow/<int:id>/<uuid:forum>/', views.add_bod_to_workflow, name="add_bod_to_workflow"),
    path('add_cpmd_to_forum/<int:id>/<uuid:forum>/', views.add_cpmd_to_forum, name="add_cpmd_to_forum"),
    path('add_secretary_to_forum/<int:id>/<uuid:forum>/', views.add_secretary_to_forum, name="add_secretary_to_forum"),
    path('delete_bod_from_workflow/<int:id>/<uuid:forum>/', views.delete_bod_from_workflow,
         name="delete_bod_from_workflow"),
    path('delete_cpmd_from_forum/<int:id>/<uuid:forum>/', views.delete_cpmd_from_forum,
         name="delete_cpmd_from_forum"),
    path('delete_secretary_from_forum/<int:id>/<uuid:forum>/', views.delete_secretary_from_forum,
         name="delete_secretary_from_forum"),
    path('list_workflow/<uuid:id>/', views.list_workflow, name="list_workflow"),
    path('list_cpmd/<uuid:id>/', views.list_cpmd, name="list_cpmd"),
    path('list_secretary/<uuid:id>/', views.list_secretary, name="list_secretary"),

    # Internal Participant
    path('update_internal/<uuid:id>/<str:op>/', views.UpdateMeetingView.as_view(), name="update_internal"),
    # path('update_internal_participant/<uuid:id>/<str:op>/', views.update_internal_participant,
    #      name="update_internal_participant"),
    path('search_participant/<uuid:id>/<str:op>/', views.search_participant,
         name="search_participant"),
    path('add_participant_to_meeting/<uuid:meet>/<int:id>/<str:op>/', views.add_participant_to_meeting,
         name="add_participant_to_meeting"),
    path('delete_participant_from_meeting/<uuid:meet>/<int:id>/<str:op>/', views.delete_participant_from_meeting,
         name="delete_participant_from_meeting"),

    # Activity
    path('list_activity/', views.list_activity, name="list_activity"),
    path('list_notes/', views.list_notes, name="list_notes"),
    path('list_update_activity/<uuid:id>/', views.list_update_activity, name="list_update_activity"),
    path('input_activity/<uuid:id>/', views.InputActivityView.as_view(), name="input_activity"),
    path('update_activity/<uuid:id>/', views.UpdateActivityView.as_view(), name="update_activity"),
    path('delete_activity/<uuid:id>/', views.DeleteActivityView.as_view(), name="delete_activity"),
    path('status_activity/<uuid:id>/<int:op>/', views.status_activity, name="status_activity"),
    path('list_activity_attachment/<uuid:id>/<uuid:meet_id>/', views.list_activity_attachment,
         name="list_activity_attachment"),

    # Finish Check
    path('finish_check/<uuid:id>/<str:op>/', views.finish_check, name="finish_check"),
    path('list_finish_check/', views.list_finish_check, name='list_finish_check'),
    path('list_approve_meeting/<uuid:id>/', views.list_approve_meeting, name='list_approve_meeting'),

    # Search
    path('search_all/', views.search_all, name="search_all"),

    # PDF
    path('create_pdf/<uuid:id>/', views.create_pdf, name='create_pdf'),

    # Status Approval
    path('status_approval/', views.status_approval, name='status_approval'),
    path('cek_status_approval/<uuid:id>/', views.cek_status_approval, name='cek_status_approval'),
    path('verify/<str:token>/', views.verify, name='verify'),

    # Complete Approve
    path('export_to_excel/<uuid:id>/', views.export_to_excel, name='export_to_excel'),
    path('view_mom_complete_approve/<uuid:id>/', views.view_mom_complete_approve, name='view_mom_complete_approve'),

    # Reminder Notifications
    # path('reminder/', views.send_activity_duedate_notifications, name='send_activity_duedate_notifications'),
]

users/urls.py
from django.urls import path
from . import views
from .forms import UserLoginForm, PwdChangeForm, PwdResetForm, PwdResetConfirmForm
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                               form_class=PwdChangeForm), name='pwdchange'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                                                 form_class=PwdResetForm), name='password_reset'),
    path('password_reset_confirm/<uid64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                                     form_class=PwdResetConfirmForm), name='password_reset_confirm'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('list_department/', views.list_department, name='list_department'),
    path('input_department/', views.InputDepartmentView.as_view(), name='input_department'),
    path('update_department/<uuid:id>/', views.UpdateDepartmentView.as_view(), name='update_department'),
    path('delete_department/<uuid:id>/', views.DeleteDepartmentView.as_view(), name='delete_department'),
    path('input_bulk_users/', views.InputBulkUsersView.as_view(), name='input_bulk_users'),
]

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'base/nav-main.html' %}
{% include 'base/show_message.html' %}
{% block content %}
{% endblock %}
{% include 'base/footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/base/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base/nav-main.html
{% load static %}
<style>
    .logo-nav {
        width: 50px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'pica:dashboard' %}" class="navbar-brand"><img class="rounded-3 logo-nav nav-img"
                                                                       src="{% static 'img/logo_epica_new.png' %}"
                                                                       alt=""
                                                                       style="width: 100px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav me-auto">
                    {% for grp in request.user.groups.all %}
                        {% if grp.name == "Secretary" %}
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    Meeting
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:list_meeting' 'I' %}" class="dropdown-item">Create</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_meeting' 'O' %}" class="dropdown-item">History</a>
                                    </li>
                                    <li><a href="{% url 'pica:status_approval' %}" class="dropdown-item">Approval
                                        Status</a>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                        {% if grp.name == "CPMD" %}
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    Master
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:list_company' %}" class="dropdown-item">Company</a></li>
                                    <li><a href="{% url 'users:list_department' %}" class="dropdown-item">Division</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    Meeting
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:list_meeting' 'I' %}" class="dropdown-item">Create</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_meeting' 'O' %}" class="dropdown-item">History</a>
                                    </li>
                                    <li><a href="{% url 'pica:status_approval' %}" class="dropdown-item">Approval
                                        Status</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_complete_approve' 'O' %}" class="dropdown-item">Complete
                                        Approve</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_outside' %}" class="dropdown-item">Outside
                                        Participant</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    PICA
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:search_all' %}" class="dropdown-item">Search</a></li>
                                    <li class="dropdown dropend">
                                        <a href="#" class="dropdown-item dropdown-toggle"
                                           id="navbar-dropdown-list-deep-1"
                                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Outstanding
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end"
                                            aria-labelledby="navbar-dropdown-link">
                                            <li><a href="{% url 'pica:overdue_all_pica' %}"
                                                   class="dropdown-item">Overdue</a></li>
                                            <li><a href="{% url 'pica:ongoing_all_pica' %}" class="dropdown-item">On
                                                Going</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                        {% if grp.name == "PIC ePica" %}
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    Master
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:list_company' %}" class="dropdown-item">Company</a></li>
                                    <li><a href="{% url 'users:list_department' %}" class="dropdown-item">Division</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_forum' %}" class="dropdown-item">Forum</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    Meeting
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:list_meeting' 'I' %}" class="dropdown-item">Create</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_meeting' 'O' %}" class="dropdown-item">History</a>
                                    </li>
                                    <li><a href="{% url 'pica:status_approval' %}" class="dropdown-item">Approval
                                        Status</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_complete_approve' %}" class="dropdown-item">Complete
                                        Approve</a>
                                    </li>
                                    <li><a href="{% url 'pica:list_outside' %}" class="dropdown-item">Outside
                                        Participant</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark fs-5" id="navbar-dropdown-link"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                                    PICA
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link">
                                    <li><a href="{% url 'pica:search_all' %}" class="dropdown-item">Search</a></li>
                                    <li class="dropdown dropend">
                                        <a href="#" class="dropdown-item dropdown-toggle"
                                           id="navbar-dropdown-list-deep-1"
                                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Outstanding
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end"
                                            aria-labelledby="navbar-dropdown-link">
                                            <li><a href="{% url 'pica:overdue_all_pica' %}"
                                                   class="dropdown-item">Overdue</a></li>
                                            <li><a href="{% url 'pica:ongoing_all_pica' %}" class="dropdown-item">On
                                                Going</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                        {% if grp.name == "BOD" %}
                            <li class="nav-item">
                                <a class="nav-link text-dark fs-5"
                                   href="{% url 'pica:list_meeting_pending' %}">Approval</a>
                            </li>
                        {% endif %}
                        {% if grp.name == "PIC" %}
                            <li class="nav-item text-white fs-5">
                                <a class="nav-link" href="{% url 'pica:list_activity' %}">Activity</a>
                            </li>
                            <li class="nav-item text-white fs-5">
                                <a class="nav-link" href="{% url 'pica:list_notes' %}">Notes</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item dropdown dropstart">
                        <a class="nav-link dropdown-toggle text-dark fs-5" data-bs-toggle="dropdown" href="#"
                           role="button"
                           aria-haspopup="true" aria-expanded="false">Profile</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'users:pwdchange' %}">Change Password</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:edit_profile' %}">Update Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        {% if user.user2profile.photo.name != '' %}
                            <picture><img class="border rounded-circle" src="{{ user.user2profile.photo.url }}"
                                          alt="b"
                                          style="width: 50px;"></picture>
                        {% else %}
                            <picture><img class="border rounded-circle" src="{% static 'img/user-3.png' %}"
                                          alt="b"
                                          style="width: 50px;"></picture>
                        {% endif %}
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark fs-5" href="{% url 'users:login' %}">Login</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

templates/base/show_message.html
{% for message in messages %}
    {% if message.tags == 'success' %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
            var m = "{{ message }}";
            swal("Success", m, "success");
        </script>
    {% endif %}
    {% if message.tags == 'error' %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
            var m = "{{ message }}";
            swal("Error", m, "error");
        </script>
    {% endif %}
    {% if message.tags == 'warning' %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
            var m = "{{ message }}";
            swal("Warning", m, "warning");
        </script>
    {% endif %}
    {% if message.tags == 'info' %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
            var m = "{{ message }}";
            swal("Warning", m, "info");
        </script>
    {% endif %}
{% endfor %}