epicaTTA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pica.urls')),    # Homepage
    path('users/', include('users.urls')), # Dashboard
    path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:  # Dev only
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pica/urls.py
from django.urls import path
from . import views

app_name = 'pica'

urlpatterns = [
    # Home
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # InCharge
    path('search_incharge/<uuid:id>/<str:op>/<uuid:tpk>/', views.search_incharge,
         name="search_incharge"),
    path('add_inputter_to_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/<str:st>/', views.add_inputter_to_topic,
         name="add_inputter_to_topic"),
    path('add_incharge_to_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.add_incharge_to_topic,
         name="add_incharge_to_topic"),
    path('delete_inputter_from_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.delete_inputter_from_topic,
         name="delete_inputter_from_topic"),
    path('delete_incharge_from_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.delete_incharge_from_topic,
         name="delete_incharge_from_topic"),

    # Company
    path('list_company/', views.list_company, name="list_company"),
    path('input_company/', views.InputCompanyView.as_view(), name="input_company"),
    path('update_company/<uuid:id>/', views.UpdateCompanyView.as_view(), name="update_company"),
    path('delete_company/<uuid:id>/', views.DeleteCompanyView.as_view(), name="delete_company"),

    # Forum
    path('list_forum/', views.list_forum, name="list_forum"),
    path('input_forum/', views.InputForumView.as_view(), name="input_forum"),
    path('update_forum/<uuid:id>/', views.UpdateForumView.as_view(), name="update_forum"),
    path('delete_forum/<uuid:id>/', views.DeleteForumView.as_view(), name="delete_forum"),

    # Meeting
    path('list_meeting/<str:op>/', views.list_meeting, name="list_meeting"),
    path('list_complete_approve/', views.list_complete_approve, name="list_complete_approve"),
    path('input_attachment/<uuid:id>/<str:op>/', views.InputAttachmentView.as_view(), name="input_attachment"),
    path('input_activity_attachment/<uuid:id>/<uuid:id2>/', views.InputActivityAttachmentView.as_view(),
         name="input_activity_attachment"),
    path('delete_lampiran/<uuid:id>/<str:op>/<uuid:id2>/', views.delete_lampiran, name="delete_lampiran"),
    path('delete_pdf/<uuid:id>/<uuid:id2>/', views.delete_pdf, name="delete_pdf"),
    path('delete_image/<uuid:id>/<uuid:id2>/', views.delete_image, name="delete_image"),
    path('input_meeting/<str:op>/', views.InputMeetingView.as_view(), name="input_meeting"),
    path('update_meeting/<uuid:id>/<str:op>/', views.UpdateMeetingView.as_view(), name="update_meeting"),

    # Meeting Approved
    path('list_meeting_pending/', views.list_meeting_pending, name="list_meeting_pending"),
    path('list_topic_review/<uuid:id>/', views.list_topic_review, name="list_topic_review"),
    path('review_topic/<uuid:tpk>/<uuid:apr>/', views.ReviewTopicView.as_view(), name="review_topic"),
    path('approve_meeting/<uuid:id>/', views.ApproveMeetingView.as_view(), name="approve_meeting"),

    # Outside Participant
    path('list_outside/', views.list_outside, name="list_outside"),
    path('input_outside/', views.InputOutsideView.as_view(), name="input_outside"),
    path('update_outside/<uuid:id>/', views.UpdateOutsideView.as_view(), name="update_outside"),
    path('update_outside_participant/<uuid:id>/<str:op>/', views.update_outside_participant,
         name="update_outside_participant"),
    path('add_outside_to_meeting/<uuid:meet>/<uuid:id>/<str:op>/', views.add_outside_to_meeting,
         name="add_outside_to_meeting"),
    path('delete_outside_from_meeting/<uuid:meet>/<uuid:id>/<str:op>/', views.delete_outside_from_meeting,
         name="delete_outside_from_meeting"),
    path('delete_outside/<uuid:id>/', views.DeleteOutsideView.as_view(), name="delete_outside"),

    # Topic
    path('input_topic/<uuid:id>/<str:op>/', views.InputTopicView.as_view(), name="input_topic"),
    path('update_pic_topic/<uuid:meet>/<uuid:id>/<str:op>/', views.update_pic_topic, name="update_pic_topic"),
    path('update_topic/<uuid:meet>/<uuid:id>/<str:op>/', views.UpdateTopicView.as_view(), name="update_topic"),
    path('add_pic_to_topic/<uuid:tpk>/<int:id>/<str:op>/', views.add_pic_to_topic,
         name="add_pic_to_topic"),
    path('delete_pic_from_topic/<uuid:tpk>/<int:id>/<str:op>/', views.delete_pic_from_topic,
         name="delete_pic_from_topic"),
    path('list_topic/<uuid:id>/<str:op>/', views.list_topic, name="list_topic"),
    path('overdue_all_pica/', views.overdue_all_pica, name='overdue_all_pica'),
    path('ongoing_all_pica/', views.ongoing_all_pica, name='ongoing_all_pica'),
    path('close_pica/<uuid:id>/', views.close_pica, name='close_pica'),
    path('change_pica_status/<uuid:id>/', views.change_pica_status, name='change_pica_status'),

    # Workflow
    path('update_workflow/<uuid:id>/', views.update_workflow, name="update_workflow"),
    path('update_cpmd/<uuid:id>/', views.update_cpmd, name="update_cpmd"),
    path('update_secretary/<uuid:id>/', views.update_secretary, name="update_secretary"),
    path('edit_workflow/<uuid:id>/<uuid:forum>/', views.EditWorkflowView.as_view(), name="edit_workflow"),
    path('add_bod_to_workflow/<int:id>/<uuid:forum>/', views.add_bod_to_workflow, name="add_bod_to_workflow"),
    path('add_cpmd_to_forum/<int:id>/<uuid:forum>/', views.add_cpmd_to_forum, name="add_cpmd_to_forum"),
    path('add_secretary_to_forum/<int:id>/<uuid:forum>/', views.add_secretary_to_forum, name="add_secretary_to_forum"),
    path('delete_bod_from_workflow/<int:id>/<uuid:forum>/', views.delete_bod_from_workflow,
         name="delete_bod_from_workflow"),
    path('delete_cpmd_from_forum/<int:id>/<uuid:forum>/', views.delete_cpmd_from_forum,
         name="delete_cpmd_from_forum"),
    path('delete_secretary_from_forum/<int:id>/<uuid:forum>/', views.delete_secretary_from_forum,
         name="delete_secretary_from_forum"),
    path('list_workflow/<uuid:id>/', views.list_workflow, name="list_workflow"),
    path('list_cpmd/<uuid:id>/', views.list_cpmd, name="list_cpmd"),
    path('list_secretary/<uuid:id>/', views.list_secretary, name="list_secretary"),

    # Internal Participant
    path('update_internal/<uuid:id>/<str:op>/', views.UpdateMeetingView.as_view(), name="update_internal"),
    # path('update_internal_participant/<uuid:id>/<str:op>/', views.update_internal_participant,
    #      name="update_internal_participant"),
    path('search_participant/<uuid:id>/<str:op>/', views.search_participant,
         name="search_participant"),
    path('add_participant_to_meeting/<uuid:meet>/<int:id>/<str:op>/', views.add_participant_to_meeting,
         name="add_participant_to_meeting"),
    path('delete_participant_from_meeting/<uuid:meet>/<int:id>/<str:op>/', views.delete_participant_from_meeting,
         name="delete_participant_from_meeting"),

    # Activity
    path('list_activity/', views.list_activity, name="list_activity"),
    path('list_notes/', views.list_notes, name="list_notes"),
    path('list_update_activity/<uuid:id>/', views.list_update_activity, name="list_update_activity"),
    path('input_activity/<uuid:id>/', views.InputActivityView.as_view(), name="input_activity"),
    path('update_activity/<uuid:id>/', views.UpdateActivityView.as_view(), name="update_activity"),
    path('delete_activity/<uuid:id>/', views.DeleteActivityView.as_view(), name="delete_activity"),
    path('status_activity/<uuid:id>/<int:op>/', views.status_activity, name="status_activity"),
    path('list_activity_attachment/<uuid:id>/<uuid:meet_id>/', views.list_activity_attachment,
         name="list_activity_attachment"),

    # Finish Check
    path('finish_check/<uuid:id>/<str:op>/', views.finish_check, name="finish_check"),
    path('list_finish_check/', views.list_finish_check, name='list_finish_check'),
    path('list_approve_meeting/<uuid:id>/', views.list_approve_meeting, name='list_approve_meeting'),

    # Search
    path('search_all/', views.search_all, name="search_all"),

    # PDF
    path('create_pdf/<uuid:id>/', views.create_pdf, name='create_pdf'),

    # Status Approval
    path('status_approval/', views.status_approval, name='status_approval'),
    path('cek_status_approval/<uuid:id>/', views.cek_status_approval, name='cek_status_approval'),
    path('verify/<str:token>/', views.verify, name='verify'),

    # Complete Approve
    path('export_to_excel/<uuid:id>/', views.export_to_excel, name='export_to_excel'),
    path('view_mom_complete_approve/<uuid:id>/', views.view_mom_complete_approve, name='view_mom_complete_approve'),

    # Reminder Notifications
    # path('reminder/', views.send_activity_duedate_notifications, name='send_activity_duedate_notifications'),
]

users/urls.py
from django.urls import path
from . import views
from .forms import UserLoginForm, PwdChangeForm, PwdResetForm, PwdResetConfirmForm
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                               form_class=PwdChangeForm), name='pwdchange'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                                                 form_class=PwdResetForm), name='password_reset'),
    path('password_reset_confirm/<uid64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                                     form_class=PwdResetConfirmForm), name='password_reset_confirm'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('list_department/', views.list_department, name='list_department'),
    path('input_department/', views.InputDepartmentView.as_view(), name='input_department'),
    path('update_department/<uuid:id>/', views.UpdateDepartmentView.as_view(), name='update_department'),
    path('delete_department/<uuid:id>/', views.DeleteDepartmentView.as_view(), name='delete_department'),
    path('input_bulk_users/', views.InputBulkUsersView.as_view(), name='input_bulk_users'),
]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, PasswordChangeForm, SetPasswordForm
from .models import Profile, Department


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ["name", "description"]


class UpdateDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ["name", "description"]


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username/Email :', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password :',
            'id': 'login-pwd',
        }
    ))


class PwdChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Old Password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'old_password'}))
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'new_password'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Retype New Password', 'id': 'retype_new_password'}))


class PwdResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        test = User.objects.filter(email=email)
        if not test:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-firstname'}))

    last_name = forms.CharField(
        label='Lastname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Lastname', 'id': 'form-lastname'}))

    # email = forms.EmailField(
    #     max_length=200, widget=forms.TextInput(
    #         attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name')

    #
    #     def clean_email(self):
    #         email = self.cleaned_data['email']
    #         if User.objects.filter(email=email).exists():
    #             raise forms.ValidationError(
    #                 'Please use another Email, that is already taken')
    #         return email
    #
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_name'].required = False
        # self.fields['email'].required = False


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['gender', 'photo', 'bod', 'mobile', 'profile2department', 'email_atasan', 'cpmd', 'secretary', 'pic_epica']

        # widgets = {
        #     'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
        # }


class InputBulkUserForm(forms.Form):
    file_content = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}))

users/templates/users/delete_department.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Delete Division{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 bg-light mt-5 px-5">
                <form action="" method="post">
                    <fieldset>
                        <legend class="text-center fs-3 fw-bold mb-5 mt-5 text-danger">Delete Division</legend>
                        {% csrf_token %}
                        <br>
                        <div class="text-center fs-5">
                            Are you sure want to delete this data?
                        </div>
                        <br>
                        <div class="row mb-3">
                            <div class="col-12">
                                Division Name : {{ department.name }}
                            </div>
                            <div class="col-12">
                                Description : {{ department.description }}
                            </div>
                        </div>
                        <div class="row mb-5 mt-5">
                            <div class="col-12">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <button class="btn btn-warning mx-3"
                                                type="submit"><i class="fa-solid fa-trash"></i>&nbsp;&nbsp;Delete
                                        </button>
                                    </div>
                                    <div>
                                        <a class="btn btn-danger mx-3"
                                           href="{% url 'users:list_department' %}"><i class="fa-solid fa-ban"></i>&nbsp;&nbsp;Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

users/templates/users/input_bulk_user.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Register User{% endblock %}
{% block content %}
    <div class="text-start d-flex justify-content-lg-center">
        <div class="row mt-5" style="width: 700px;height: 350px;">
            <div class="col d-flex justify-content-lg-center align-items-lg-center"
                 style="background: var(--bs-gray-300);border: 1px solid var(--bs-gray-400) ;"><img class="img-fluid"
                                                                                                    src="{% static 'img/logo_epica_new.png' %}"
                                                                                                    style="width: 250px;height: 200px;"
                                                                                                    alt="ePicaLogo">
            </div>
            <div class="col" style="border: 1px solid var(--bs-gray-400) ;">
                <h2 class="mt-3 mb-2 m">Input Bulk User</h2>
                <form method="post" style="font-family: Roboto, sans-serif;" enctype="multipart/form-data">
                    {% csrf_token %}
                    <br><br>
                    {{ form.as_p }}
                    <div>
                        <div class="row mt-5">
                            <div class="col">
                                <button class="btn btn-primary border rounded-pill mb-2" type="submit"
                                        style="width: 100%;font-family: 'Open Sans', sans-serif;">Process
                                </button>
                            </div>
                            <div class="col"><a class="btn btn-danger border rounded-pill" role="button"
                                                style="width: 100%;" href="{% url 'pica:home' %}">Cancel</a></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/input_department.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Input Division{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 bg-light mt-5 px-5">
                <form action="" method="post" enctype="multipart/form-data">
                    <fieldset>
                        <legend class="text-center fs-4 fw-bold mb-5 mt-5">Input Division</legend>
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-12">
                                <label class="form-label">Division Name :</label>
                                {% render_field form.name placeholder="Division Name" class+="form-control" %}
                            </div>
                            <br>
                            <div class="col-12 mt-3">
                                <label class="form-label">Description :</label>
                                {% render_field form.description placeholder="Description" class+="form-control" %}
                            </div>
                        </div>
                        <div class="row mb-5 mt-5">
                            <div class="col-12">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <button class="btn btn-success mx-3"
                                                type="submit"><i class="fa-solid fa-floppy-disk"></i>&nbsp;&nbsp;Save
                                        </button>
                                    </div>
                                    <div>
                                        <a class="btn btn-danger mx-3"
                                           href="{% url 'users:list_department' %}"><i class="fa-solid fa-xmark"></i>&nbsp;&nbsp;Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

users/templates/users/list_department.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}List Division{% endblock %}
{% block content %}
    <style>
        .scroll {
            height: 550px;
            overflow: scroll;
        }
    </style>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 bg-light mt-3 px-5">
                <div class="text-center fs-4 fw-bold mb-3 mt-3">List Division</div>
                <br>
                <div>
                    <a href="{% url 'users:input_department' %}" class="btn btn-warning"><i
                            class="fa-solid fa-circle-plus"></i>&nbsp;&nbsp;Add Division</a>
                    <a href="{% url 'pica:dashboard' %}" class="btn btn-danger"><i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back
                        to Dashboard</a>
                </div>
                <br>
                <div class="scroll">
                    <table class="table table-light">
                        <thead>
                        <tr>
                            <th>Division</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for department in departments %}
                            <tr>
                                <td>{{ department.name }}</td>
                                <td>{{ department.description }}</td>
                                <td><a href="{% url 'users:update_department' department.id %}"
                                       class="btn btn-outline-warning"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;Update</a>
                                </td>
                                <td>
                                    <a class='btn btn-outline-danger'
                                       href="{% url 'users:delete_department' department.id %}"><i
                                            class="fa-solid fa-trash"></i>&nbsp;&nbsp;Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

users/templates/users/update_department.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Update Division{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 bg-light mt-5 px-5">
                <form action="" method="post" enctype="multipart/form-data">
                    <fieldset>
                        <legend class="text-center fs-4 fw-bold mb-5 mt-5">Update Division</legend>
                        {% csrf_token %}
                        <div class="row mb-3">
                            {#                            <div class="col-12">#}
                            {#                                <label class="form-label fw-bold">Div/Dept. Name :</label>#}
                            {#                                <strong>{{ department.description }}</strong>#}
                            {#                            </div>#}
                            <br>
                            <div class="col-12 mt-3">
                                <label class="form-label">Division :</label>
                                {% render_field form.name placeholder="Division" class+="form-control" %}
                            </div>
                            <div class="col-12 mt-3">
                                <label class="form-label">Description :</label>
                                {% render_field form.description placeholder="Description" class+="form-control" %}
                            </div>
                        </div>
                        <div class="row mb-5 mt-5">
                            <div class="col-12">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <button class="btn btn-warning mx-3"
                                                type="submit"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;Update
                                        </button>
                                    </div>
                                    <div>
                                        <a class="btn btn-danger mx-3"
                                           href="{% url 'users:list_department' %}"><i class="fa-solid fa-ban"></i>&nbsp;&nbsp;Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

users/templates/users/update_profile.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Edit your account{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-7 bg-light mt-5 px-5">
                <form action="" method="post" enctype="multipart/form-data">
                    <fieldset>
                        <legend class="text-center fs-4 fw-bold mb-5 mt-5">Update Profile</legend>
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-5 mb-4">
                                <label class="form-label fs-5 fw-bold mb-3">Username
                                    : {{ user_profile.profile2user.username }}</label>
                            </div>
                            <div class="col-7 mb-4">
                                <label class="form-label fs-5 fw-bold mb-3">Full Name
                                    : {{ user_profile.profile2user.first_name }} {{ user_profile.profile2user.last_name }}</label>
                            </div>
                            <div class="col-4">
                                <label class="form-label">Gender :</label>
                                {{ profile_form.gender }}
                            </div>
                            <div class="col-4">
                                <label class="form-label">Mobile :</label>
                                {{ profile_form.mobile }}
                            </div>
                            <div class="col-4">
                                <label class="form-label">Status Karyawan :</label>
                                {{ profile_form.bod }}
                            </div>
                            <div class="col-4 mt-3">
                                <label class="form-label">Division :</label>
                                {{ profile_form.profile2department }}
                            </div>
                            <div class="col-4 mt-3">
                                <label class="form-label">Email Atasan :</label>
                                {{ profile_form.email_atasan }}
                            </div>
                            <div class="col-4 mt-3">
                                <label class="form-label">Team CPMD :</label>
                                {{ profile_form.cpmd }}
                            </div>
                        </div>
                        <hr class="mt-5 mb-5">
                        <div class="row mt-5 mb-3">
                            <div class="col-6">
                                <label class="form-label" for="">Photo Profile :</label>
                                {{ profile_form.photo }}
                            </div>
                            <div class="col-6 text-center">
                                {% if user_profile.photo.url %}
                                    <img class="border border-3 p-4" src="{{ user_profile.photo.url }}" alt=""
                                         style="width: 200px; height: 200px;">
                                {% else %}
                                    <img class="border border-3 p-4" src="{% static 'img/user.png' %}" alt=""
                                         style="width: 200px; height: 200px;">
                                {% endif %}
                            </div>
                        </div>
                        <div class="row mb-5 mt-5">
                            <div class="col-12">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <button class="btn btn-warning mx-3"
                                                type="submit"><i class="fa-solid fa-floppy-disk"></i>&nbsp;&nbsp;Save
                                            Changes
                                        </button>
                                    </div>
                                    <div>
                                        <a class="btn btn-danger mx-3" href="{% url 'pica:dashboard' %}"><i
                                                class="fa-solid fa-ban"></i>&nbsp;&nbsp;Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}