epicaTTA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pica.urls')),    # Homepage
    path('users/', include('users.urls')), # Dashboard
    path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:  # Dev only
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pica/urls.py
from django.urls import path
from . import views

app_name = 'pica'

urlpatterns = [
    # Home
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # InCharge
    path('search_incharge/<uuid:id>/<str:op>/<uuid:tpk>/', views.search_incharge,
         name="search_incharge"),
    path('add_inputter_to_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/<str:st>/', views.add_inputter_to_topic,
         name="add_inputter_to_topic"),
    path('add_incharge_to_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.add_incharge_to_topic,
         name="add_incharge_to_topic"),
    path('delete_inputter_from_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.delete_inputter_from_topic,
         name="delete_inputter_from_topic"),
    path('delete_incharge_from_topic/<uuid:id>/<str:op>/<uuid:tpk>/<int:usr>/', views.delete_incharge_from_topic,
         name="delete_incharge_from_topic"),

    # Company
    path('list_company/', views.list_company, name="list_company"),
    path('input_company/', views.InputCompanyView.as_view(), name="input_company"),
    path('update_company/<uuid:id>/', views.UpdateCompanyView.as_view(), name="update_company"),
    path('delete_company/<uuid:id>/', views.DeleteCompanyView.as_view(), name="delete_company"),

    # Forum
    path('list_forum/', views.list_forum, name="list_forum"),
    path('input_forum/', views.InputForumView.as_view(), name="input_forum"),
    path('update_forum/<uuid:id>/', views.UpdateForumView.as_view(), name="update_forum"),
    path('delete_forum/<uuid:id>/', views.DeleteForumView.as_view(), name="delete_forum"),

    # Meeting
    path('list_meeting/<str:op>/', views.list_meeting, name="list_meeting"),
    path('list_complete_approve/', views.list_complete_approve, name="list_complete_approve"),
    path('input_attachment/<uuid:id>/<str:op>/', views.InputAttachmentView.as_view(), name="input_attachment"),
    path('input_activity_attachment/<uuid:id>/<uuid:id2>/', views.InputActivityAttachmentView.as_view(),
         name="input_activity_attachment"),
    path('delete_lampiran/<uuid:id>/<str:op>/<uuid:id2>/', views.delete_lampiran, name="delete_lampiran"),
    path('delete_pdf/<uuid:id>/<uuid:id2>/', views.delete_pdf, name="delete_pdf"),
    path('delete_image/<uuid:id>/<uuid:id2>/', views.delete_image, name="delete_image"),
    path('input_meeting/<str:op>/', views.InputMeetingView.as_view(), name="input_meeting"),
    path('update_meeting/<uuid:id>/<str:op>/', views.UpdateMeetingView.as_view(), name="update_meeting"),

    # Meeting Approved
    path('list_meeting_pending/', views.list_meeting_pending, name="list_meeting_pending"),
    path('list_topic_review/<uuid:id>/', views.list_topic_review, name="list_topic_review"),
    path('review_topic/<uuid:tpk>/<uuid:apr>/', views.ReviewTopicView.as_view(), name="review_topic"),
    path('approve_meeting/<uuid:id>/', views.ApproveMeetingView.as_view(), name="approve_meeting"),

    # Outside Participant
    path('list_outside/', views.list_outside, name="list_outside"),
    path('input_outside/', views.InputOutsideView.as_view(), name="input_outside"),
    path('update_outside/<uuid:id>/', views.UpdateOutsideView.as_view(), name="update_outside"),
    path('update_outside_participant/<uuid:id>/<str:op>/', views.update_outside_participant,
         name="update_outside_participant"),
    path('add_outside_to_meeting/<uuid:meet>/<uuid:id>/<str:op>/', views.add_outside_to_meeting,
         name="add_outside_to_meeting"),
    path('delete_outside_from_meeting/<uuid:meet>/<uuid:id>/<str:op>/', views.delete_outside_from_meeting,
         name="delete_outside_from_meeting"),
    path('delete_outside/<uuid:id>/', views.DeleteOutsideView.as_view(), name="delete_outside"),

    # Topic
    path('input_topic/<uuid:id>/<str:op>/', views.InputTopicView.as_view(), name="input_topic"),
    path('update_pic_topic/<uuid:meet>/<uuid:id>/<str:op>/', views.update_pic_topic, name="update_pic_topic"),
    path('update_topic/<uuid:meet>/<uuid:id>/<str:op>/', views.UpdateTopicView.as_view(), name="update_topic"),
    path('add_pic_to_topic/<uuid:tpk>/<int:id>/<str:op>/', views.add_pic_to_topic,
         name="add_pic_to_topic"),
    path('delete_pic_from_topic/<uuid:tpk>/<int:id>/<str:op>/', views.delete_pic_from_topic,
         name="delete_pic_from_topic"),
    path('list_topic/<uuid:id>/<str:op>/', views.list_topic, name="list_topic"),
    path('overdue_all_pica/', views.overdue_all_pica, name='overdue_all_pica'),
    path('ongoing_all_pica/', views.ongoing_all_pica, name='ongoing_all_pica'),
    path('close_pica/<uuid:id>/', views.close_pica, name='close_pica'),
    path('change_pica_status/<uuid:id>/', views.change_pica_status, name='change_pica_status'),

    # Workflow
    path('update_workflow/<uuid:id>/', views.update_workflow, name="update_workflow"),
    path('update_cpmd/<uuid:id>/', views.update_cpmd, name="update_cpmd"),
    path('update_secretary/<uuid:id>/', views.update_secretary, name="update_secretary"),
    path('edit_workflow/<uuid:id>/<uuid:forum>/', views.EditWorkflowView.as_view(), name="edit_workflow"),
    path('add_bod_to_workflow/<int:id>/<uuid:forum>/', views.add_bod_to_workflow, name="add_bod_to_workflow"),
    path('add_cpmd_to_forum/<int:id>/<uuid:forum>/', views.add_cpmd_to_forum, name="add_cpmd_to_forum"),
    path('add_secretary_to_forum/<int:id>/<uuid:forum>/', views.add_secretary_to_forum, name="add_secretary_to_forum"),
    path('delete_bod_from_workflow/<int:id>/<uuid:forum>/', views.delete_bod_from_workflow,
         name="delete_bod_from_workflow"),
    path('delete_cpmd_from_forum/<int:id>/<uuid:forum>/', views.delete_cpmd_from_forum,
         name="delete_cpmd_from_forum"),
    path('delete_secretary_from_forum/<int:id>/<uuid:forum>/', views.delete_secretary_from_forum,
         name="delete_secretary_from_forum"),
    path('list_workflow/<uuid:id>/', views.list_workflow, name="list_workflow"),
    path('list_cpmd/<uuid:id>/', views.list_cpmd, name="list_cpmd"),
    path('list_secretary/<uuid:id>/', views.list_secretary, name="list_secretary"),

    # Internal Participant
    path('update_internal/<uuid:id>/<str:op>/', views.UpdateMeetingView.as_view(), name="update_internal"),
    # path('update_internal_participant/<uuid:id>/<str:op>/', views.update_internal_participant,
    #      name="update_internal_participant"),
    path('search_participant/<uuid:id>/<str:op>/', views.search_participant,
         name="search_participant"),
    path('add_participant_to_meeting/<uuid:meet>/<int:id>/<str:op>/', views.add_participant_to_meeting,
         name="add_participant_to_meeting"),
    path('delete_participant_from_meeting/<uuid:meet>/<int:id>/<str:op>/', views.delete_participant_from_meeting,
         name="delete_participant_from_meeting"),

    # Activity
    path('list_activity/', views.list_activity, name="list_activity"),
    path('list_notes/', views.list_notes, name="list_notes"),
    path('list_update_activity/<uuid:id>/', views.list_update_activity, name="list_update_activity"),
    path('input_activity/<uuid:id>/', views.InputActivityView.as_view(), name="input_activity"),
    path('update_activity/<uuid:id>/', views.UpdateActivityView.as_view(), name="update_activity"),
    path('delete_activity/<uuid:id>/', views.DeleteActivityView.as_view(), name="delete_activity"),
    path('status_activity/<uuid:id>/<int:op>/', views.status_activity, name="status_activity"),
    path('list_activity_attachment/<uuid:id>/<uuid:meet_id>/', views.list_activity_attachment,
         name="list_activity_attachment"),

    # Finish Check
    path('finish_check/<uuid:id>/<str:op>/', views.finish_check, name="finish_check"),
    path('list_finish_check/', views.list_finish_check, name='list_finish_check'),
    path('list_approve_meeting/<uuid:id>/', views.list_approve_meeting, name='list_approve_meeting'),

    # Search
    path('search_all/', views.search_all, name="search_all"),

    # PDF
    path('create_pdf/<uuid:id>/', views.create_pdf, name='create_pdf'),

    # Status Approval
    path('status_approval/', views.status_approval, name='status_approval'),
    path('cek_status_approval/<uuid:id>/', views.cek_status_approval, name='cek_status_approval'),
    path('verify/<str:token>/', views.verify, name='verify'),

    # Complete Approve
    path('export_to_excel/<uuid:id>/', views.export_to_excel, name='export_to_excel'),
    path('view_mom_complete_approve/<uuid:id>/', views.view_mom_complete_approve, name='view_mom_complete_approve'),

    # Reminder Notifications
    # path('reminder/', views.send_activity_duedate_notifications, name='send_activity_duedate_notifications'),
]

pica/forms.py
from django import forms
from .models import Company, Forum, Workflow, Meeting, Topic, Department, Outside, Activity
from django.core.exceptions import ValidationError


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ["activity_date", "action_description"]
        exclude = ["activity2topic", "activity2user"]


class UpdateActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ["action_description"]
        exclude = ["activity2topic", "activity2user", "activity_date"]


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["topic_name", "problem_info", "action", "due_date", "status", "category", "topic2department",
                  "topic2company", "to_ref_no"]
        exclude = ["topic2meeting", "topic2user", "topic2incharge"]


class UpdateTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["topic_name", "problem_info", "action", "due_date", "status", "category", "topic2department",
                  "topic2company", "to_ref_no"]
        exclude = ["topic2meeting", "topic2user", "topic2incharge"]


class ReviewTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["problem_info", "action", "due_date"]
        exclude = ["topic2meeting", "topic2user", "topic2department", "status", "topic2company",
                   "topic_name"]


class MeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ["meeting_date", "start_time", "end_time", "notulen", "location", "meeting2forum"]


class UpdateMeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ["meeting_date", "start_time", "end_time", "notulen", "location"]


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ["name", "short_code", "logo", "status_active", "company_type"]


class OutsideForm(forms.ModelForm):
    class Meta:
        model = Outside
        fields = ["fullname", "email", "company_from", "mobile"]


class UpdateCompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ["short_code", "logo", "status_active", "company_type"]


class ForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ["forum_name", "description"]


class UpdateForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ["description"]


class WorkflowForm(forms.ModelForm):
    class Meta:
        model = Workflow
        fields = ["position", "workflow2user"]


class EditWorkflowForm(forms.ModelForm):
    class Meta:
        model = Workflow
        fields = ["position", "sequence_no"]


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class UploadFileForm(forms.Form):
    files = MultipleFileField(required=False)

    def clean_files(self):
        """Make sure only pdf can be uploaded."""
        files = self.files.getlist("files")
        for f in files:
            if f.content_type != "application/pdf":
                raise ValidationError('File not supported!')


class UploadAttachmentsForm(forms.Form):
    files1 = MultipleFileField(required=False)
    files2 = MultipleFileField(required=False)

    # def clean_files(self):
    #     # """Make sure only pdf can be uploaded."""
    #     files1 = self.files.getlist("files1")
    #     for f in files1:
    #         if f.content_type != "application/pdf":
    #             raise ValidationError('File must be in pdf format!')
    #
    #     # """Make sure only image file can be uploaded."""
    #     files2 = self.files.getlist("files2")
    #     for f in files2:
    #         if f.content_type not in ["image/jpeg", "image/jpg", "image/png"]:
    #             raise ValidationError('File must be in jpeg/jpg/png format!')
# class InChargeForm(forms.ModelForm):
#     class Meta:
#         model = InCharge
#         fields = ["full_name", "email"]

pica/templates/pica/activity_attachments.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Activity Attachments{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-8 bg-light mt-5 px-5">
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    <fieldset>
                        <legend class="text-center fs-4 fw-bold mb-5 mt-2">Activity Attachments</legend>
                        <div>
                            <h6>Forum : {{ meeting.meeting2forum.forum_name }}</h6>
                            <h6>Date : {{ meeting.meeting_date|date:"l, d M Y" }}</h6>
                        </div>
                        {% csrf_token %}
                        <br>
                        <p class="fw-bold">Total Size All Attachment : {{ total_size|filesizeformat }} (Max 25MB)</p>
                        <div class="row mb-3">
                            <div class="col-12 mt-3">
                                <label class="form-label">File Attachment (only pdf files) :</label>
                                {% render_field form.files1 class+="form-control" %}
                                <div class="text-center text-danger">
                                    {{ form.files1.errors }}
                                </div>
                            </div>
                            <br>
                            <div class="col-12">
                                <br>
                                <h6>Uploaded Files (pdf):</h6>
                                <table class="table table-bordered table-secondary">
                                    <thead>
                                    <tr>
                                        <th>Name of file</th>
                                        <th>Size</th>
                                        <th>Action</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for doc in doc_pdfs %}
                                        <tr>
                                            <td>{{ doc.doc_pdf.name }}</td>
                                            <td>{{ doc.doc_pdf.size|filesizeformat }}</td>
                                            <td><a href="{{ doc.doc_pdf.url }}" class="btn btn-primary"
                                                   target="_blank"><i
                                                    class="fa-solid fa-eye fa-lg"></i>&nbsp;View</a>
                                            </td>
                                            <td><a href="{% url 'pica:delete_pdf' meeting.id doc.id %}"
                                                   class="btn btn-danger"><i
                                                    class="fa-solid fa-trash fa-lg"></i>&nbsp;Remove</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-12 mt-2">
                                <label class="form-label">File Attachment (only jpeg/jpg/png files) :</label>
                                {% render_field form.files2 class+="form-control" %}
                                <div class="text-center text-danger">
                                    {{ form.files2.errors }}
                                </div>
                            </div>
                            <br>
                            <div class="col-12 mt-3">
                                <h6>Uploaded Files (jpeg/jpg/png):</h6>
                                <table class="table table-bordered table-secondary">
                                    <thead>
                                    <tr>
                                        <th>Name of file</th>
                                        <th>Size</th>
                                        <th>Action</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for doc in doc_images %}
                                        <tr>
                                            <td>{{ doc.doc_image.name }}</td>
                                            <td>{{ doc.doc_image.size|filesizeformat }}</td>
                                            <td><a href="{{ doc.doc_image.url }}" class="btn btn-primary"
                                                   target="_blank"><i
                                                    class="fa-solid fa-eye fa-lg"></i>&nbsp;View</a>
                                            </td>
                                            <td><a href="{% url 'pica:delete_image' meeting.id doc.id %}"
                                                   class="btn btn-danger"><i
                                                    class="fa-solid fa-trash fa-lg"></i>&nbsp;Remove</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <br>
                        <div class="row mb-5 mt-5">
                            <div class="col-12">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <button class="btn btn-success mx-3"
                                                type="submit">Save
                                        </button>
                                    </div>
                                    <div>
                                        <a class="btn btn-danger mx-3"
                                           href="{% url 'pica:list_update_activity' topic.id %}">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

pica/templates/pica/list_outside.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}List Outside Participants{% endblock %}
{% block content %}
    <style>
        .scroll {
            height: 550px;
            overflow: scroll;
        }
    </style>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-7 bg-light mt-3 px-5">
                <div class="text-center fs-4 fw-bold mb-3 mt-3">List Outside Participants</div>
                <br>
                <div>
                    <a href="{% url 'pica:input_outside' %}" class="btn btn-warning"><i
                            class="fa-solid fa-circle-plus"></i>&nbsp;&nbsp;Add Participant</a>
                    <a href="{% url 'pica:dashboard' %}" class="btn btn-danger"><i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back
                        to Dashboard</a>
                </div>
                <br>
                <div class="scroll">
                    <table class="table table-light">
                        <thead>
                        <tr>
                            <th>Participant Name</th>
                            <th>Email</th>
                            <th>Company</th>
                            <th>Mobile</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for outside in outsides %}
                            <tr>
                                <td>{{ outside.fullname }}</td>
                                <td>{{ outside.email }}</td>
                                <td>{{ outside.company_from }}</td>
                                <td>{{ outside.mobile }}</td>
                                <td><a href="{% url 'pica:update_outside' outside.id %}" class="btn btn-outline-warning"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;Update</a>
                                </td>
                                <td>
                                    <a class='btn btn-outline-danger' href="{% url 'pica:delete_outside' outside.id %}"><i
                                            class="fa-solid fa-trash"></i>&nbsp;&nbsp;Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

pica/templates/pica/list_secretary.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}List PIC Secreatary in Forum{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 bg-light mt-5 px-5">
                <div class="text-center fs-4 fw-bold mb-3 mt-5">List PIC Secretary in Forum</div>
                <br>
                <div class="fw-bold mb-3 fs-5">
                    Forum : {{ forum.forum_name }}
                </div>
                <div>
                    <a href="{% url 'pica:update_secretary' forum.id %}" class="btn btn-warning"><i
                            class="fa-solid fa-circle-plus"></i>&nbsp;&nbsp;Add/Remove PIC Secretary</a>
                    <a href="{% url 'pica:list_forum' %}" class="btn btn-danger"><i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back
                        to Forum</a>
                </div>
                <br>
                <table class="table table-light">
                    <thead>
                    <tr>
                        <th>Secretary Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for secretary in secretaries_in_forum %}
                        <tr>
                            <td>{{ secretary.first_name }} {{ secretary.last_name }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

pica/templates/pica/list_topic.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}List Topics{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 bg-light mt-5 px-5">
                <div class="text-center fs-4 fw-bold mb-5 mt-5">List Topics</div>
                <br>
                <div>
                    <a href="{% url 'pica:input_topic' meeting.id op %}" class="btn btn-warning"><i
                            class="fa-solid fa-circle-plus"></i>&nbsp;&nbsp;Add Topic</a>
                    <a href="{% url 'pica:list_meeting' op %}" class="btn btn-danger"><i
                            class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back to List Meeting</a>
                </div>
                <br>
                <table class="table table-light">
                    <thead>
                    <tr>
                        <th>Topic</th>
                        <th>Division</th>
                        <th>Company</th>
                        <th>Problem Identification</th>
                        <th>Corrective Action</th>
                        <th>Due Date</th>
                        <th>PIC (inputter)</th>
                        <th>PIC (PICA)</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for topic in topics %}
                        <tr>
                            <td>{{ topic.topic_name }}</td>
                            <td>{{ topic.topic2department.name }}</td>
                            <td>{{ topic.topic2company.name }}</td>
                            <td>{{ topic.problem_info }}</td>
                            <td>{{ topic.action }}</td>
                            <td>{{ topic.due_date|date:"d M Y" }}</td>
                            <td>{{ topic.topic2user.first_name }} {{ topic.topic2user.last_name }}</td>
                            <td>{{ topic.topic2incharge.first_name }} {{ topic.topic2incharge.last_name }}</td>
                            {% if topic.category == "FU" %}
                                <td>Follow Up</td>
                            {% endif %}
                            {% if topic.category == "PJ" %}
                                <td>Project</td>
                            {% endif %}
                            {% if topic.category == "PL" %}
                                <td>Policy</td>
                            {% endif %}
                            {% if topic.category == "NT" %}
                                <td>Notes</td>
                            {% endif %}
                            {% if topic.status == "O" %}
                                <td>Open</td>
                            {% endif %}
                            {% if topic.status == "C" %}
                                <td>Closed</td>
                            {% endif %}
                            {% if topic.status == "P" %}
                                <td>Progress</td>
                            {% endif %}
                            {% if topic.status == "H" %}
                                <td>Hold</td>
                            {% endif %}
                            {% if topic.status != "C" %}
                                <td><a href="{% url 'pica:update_topic' meeting.id topic.id op %}"
                                       class="btn btn-warning"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;Update</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}

pica/templates/pica/list_workflow.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}List Workflow{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 bg-light mt-3 px-5">
                <div class="text-center fs-4 fw-bold mb-3 mt-3">List Workflow</div>
                <br>
                <div class="fw-bold fs-5 mb-3">
                    Forum : {{ forum.forum_name }}
                </div>
                <div>
                    <a href="{% url 'pica:update_workflow' forum.id %}" class="btn btn-warning"><i
                            class="fa-solid fa-circle-plus"></i>&nbsp;&nbsp;Add Workflow</a>
                    <a href="{% url 'pica:list_forum' %}" class="btn btn-danger"><i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back
                        to Forum</a>
                </div>
                <br>
                <table class="table table-light">
                    <thead>
                    <tr>
                        <th>BOD Name</th>
                        <th>Position</th>
                        <th>Sequence No</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for workflow in current_workflow %}
                        <tr>
                            <td>{{ workflow.bod_name }}</td>
                            <td>{{ workflow.position }}</td>
                            <td>{{ workflow.sequence_no }}</td>
                            <td><a href="{% url 'pica:edit_workflow' workflow.id forum.id %}"
                                   class="btn btn-outline-warning"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;Edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
    {#    {% include "base/footer.html" %}#}
{% endblock %}